apiVersion: v1
kind: Service
metadata:
  name: wav-to-flac-converter
spec:
  type: LoadBalancer 
  ports:
    - name: http
      port: 80 
      protocol: TCP
      targetPort: 8080
  selector:
    app: wav-to-flac-converter

