# apiVersion: v1
# kind: Service
# metadata:
#   name: wav-to-flac-converter
# spec:
#   selector:
#     app: wav-to-flac-converter
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080 
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: wav-to-flac-converter
spec:
  type: LoadBalancer 
  ports:
    - name: http
      port: 80 
      protocol: TCP
      targetPort: 8080
  selector:
    app: wav-to-flac-converter

